version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: jip_postgres
    environment:
      POSTGRES_USER: jip
      POSTGRES_PASSWORD: jip
      POSTGRES_DB: jip
    ports:
      - '5432:5432'
    volumes:
      - jip_postgres_data:/var/lib/postgresql/data

volumes:
  jip_postgres_data:
